
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `init_table` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model init_table
 * 
 */
export type init_tableModel = runtime.Types.Result.DefaultSelection<Prisma.$init_tablePayload>

export type AggregateInit_table = {
  _count: Init_tableCountAggregateOutputType | null
  _avg: Init_tableAvgAggregateOutputType | null
  _sum: Init_tableSumAggregateOutputType | null
  _min: Init_tableMinAggregateOutputType | null
  _max: Init_tableMaxAggregateOutputType | null
}

export type Init_tableAvgAggregateOutputType = {
  id: number | null
}

export type Init_tableSumAggregateOutputType = {
  id: number | null
}

export type Init_tableMinAggregateOutputType = {
  id: number | null
}

export type Init_tableMaxAggregateOutputType = {
  id: number | null
}

export type Init_tableCountAggregateOutputType = {
  id: number
  _all: number
}


export type Init_tableAvgAggregateInputType = {
  id?: true
}

export type Init_tableSumAggregateInputType = {
  id?: true
}

export type Init_tableMinAggregateInputType = {
  id?: true
}

export type Init_tableMaxAggregateInputType = {
  id?: true
}

export type Init_tableCountAggregateInputType = {
  id?: true
  _all?: true
}

export type Init_tableAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which init_table to aggregate.
   */
  where?: Prisma.init_tableWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of init_tables to fetch.
   */
  orderBy?: Prisma.init_tableOrderByWithRelationInput | Prisma.init_tableOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.init_tableWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` init_tables from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` init_tables.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned init_tables
  **/
  _count?: true | Init_tableCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Init_tableAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Init_tableSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Init_tableMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Init_tableMaxAggregateInputType
}

export type GetInit_tableAggregateType<T extends Init_tableAggregateArgs> = {
      [P in keyof T & keyof AggregateInit_table]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateInit_table[P]>
    : Prisma.GetScalarType<T[P], AggregateInit_table[P]>
}




export type init_tableGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.init_tableWhereInput
  orderBy?: Prisma.init_tableOrderByWithAggregationInput | Prisma.init_tableOrderByWithAggregationInput[]
  by: Prisma.Init_tableScalarFieldEnum[] | Prisma.Init_tableScalarFieldEnum
  having?: Prisma.init_tableScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Init_tableCountAggregateInputType | true
  _avg?: Init_tableAvgAggregateInputType
  _sum?: Init_tableSumAggregateInputType
  _min?: Init_tableMinAggregateInputType
  _max?: Init_tableMaxAggregateInputType
}

export type Init_tableGroupByOutputType = {
  id: number
  _count: Init_tableCountAggregateOutputType | null
  _avg: Init_tableAvgAggregateOutputType | null
  _sum: Init_tableSumAggregateOutputType | null
  _min: Init_tableMinAggregateOutputType | null
  _max: Init_tableMaxAggregateOutputType | null
}

export type GetInit_tableGroupByPayload<T extends init_tableGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Init_tableGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Init_tableGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Init_tableGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Init_tableGroupByOutputType[P]>
      }
    >
  >



export type init_tableWhereInput = {
  AND?: Prisma.init_tableWhereInput | Prisma.init_tableWhereInput[]
  OR?: Prisma.init_tableWhereInput[]
  NOT?: Prisma.init_tableWhereInput | Prisma.init_tableWhereInput[]
  id?: Prisma.IntFilter<"init_table"> | number
}

export type init_tableOrderByWithRelationInput = {
  id?: Prisma.SortOrder
}

export type init_tableWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.init_tableWhereInput | Prisma.init_tableWhereInput[]
  OR?: Prisma.init_tableWhereInput[]
  NOT?: Prisma.init_tableWhereInput | Prisma.init_tableWhereInput[]
}, "id">

export type init_tableOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  _count?: Prisma.init_tableCountOrderByAggregateInput
  _avg?: Prisma.init_tableAvgOrderByAggregateInput
  _max?: Prisma.init_tableMaxOrderByAggregateInput
  _min?: Prisma.init_tableMinOrderByAggregateInput
  _sum?: Prisma.init_tableSumOrderByAggregateInput
}

export type init_tableScalarWhereWithAggregatesInput = {
  AND?: Prisma.init_tableScalarWhereWithAggregatesInput | Prisma.init_tableScalarWhereWithAggregatesInput[]
  OR?: Prisma.init_tableScalarWhereWithAggregatesInput[]
  NOT?: Prisma.init_tableScalarWhereWithAggregatesInput | Prisma.init_tableScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"init_table"> | number
}

export type init_tableCreateInput = {

}

export type init_tableUncheckedCreateInput = {
  id?: number
}

export type init_tableUpdateInput = {

}

export type init_tableUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type init_tableCreateManyInput = {
  id?: number
}

export type init_tableUpdateManyMutationInput = {

}

export type init_tableUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type init_tableCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type init_tableAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type init_tableMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type init_tableMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type init_tableSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type init_tableSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
}, ExtArgs["result"]["init_table"]>



export type init_tableSelectScalar = {
  id?: boolean
}

export type init_tableOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id", ExtArgs["result"]["init_table"]>

export type $init_tablePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "init_table"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
  }, ExtArgs["result"]["init_table"]>
  composites: {}
}

export type init_tableGetPayload<S extends boolean | null | undefined | init_tableDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$init_tablePayload, S>

export type init_tableCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<init_tableFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Init_tableCountAggregateInputType | true
  }

export interface init_tableDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['init_table'], meta: { name: 'init_table' } }
  /**
   * Find zero or one Init_table that matches the filter.
   * @param {init_tableFindUniqueArgs} args - Arguments to find a Init_table
   * @example
   * // Get one Init_table
   * const init_table = await prisma.init_table.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends init_tableFindUniqueArgs>(args: Prisma.SelectSubset<T, init_tableFindUniqueArgs<ExtArgs>>): Prisma.Prisma__init_tableClient<runtime.Types.Result.GetResult<Prisma.$init_tablePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Init_table that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {init_tableFindUniqueOrThrowArgs} args - Arguments to find a Init_table
   * @example
   * // Get one Init_table
   * const init_table = await prisma.init_table.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends init_tableFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, init_tableFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__init_tableClient<runtime.Types.Result.GetResult<Prisma.$init_tablePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Init_table that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {init_tableFindFirstArgs} args - Arguments to find a Init_table
   * @example
   * // Get one Init_table
   * const init_table = await prisma.init_table.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends init_tableFindFirstArgs>(args?: Prisma.SelectSubset<T, init_tableFindFirstArgs<ExtArgs>>): Prisma.Prisma__init_tableClient<runtime.Types.Result.GetResult<Prisma.$init_tablePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Init_table that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {init_tableFindFirstOrThrowArgs} args - Arguments to find a Init_table
   * @example
   * // Get one Init_table
   * const init_table = await prisma.init_table.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends init_tableFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, init_tableFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__init_tableClient<runtime.Types.Result.GetResult<Prisma.$init_tablePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Init_tables that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {init_tableFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Init_tables
   * const init_tables = await prisma.init_table.findMany()
   * 
   * // Get first 10 Init_tables
   * const init_tables = await prisma.init_table.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const init_tableWithIdOnly = await prisma.init_table.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends init_tableFindManyArgs>(args?: Prisma.SelectSubset<T, init_tableFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$init_tablePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Init_table.
   * @param {init_tableCreateArgs} args - Arguments to create a Init_table.
   * @example
   * // Create one Init_table
   * const Init_table = await prisma.init_table.create({
   *   data: {
   *     // ... data to create a Init_table
   *   }
   * })
   * 
   */
  create<T extends init_tableCreateArgs>(args: Prisma.SelectSubset<T, init_tableCreateArgs<ExtArgs>>): Prisma.Prisma__init_tableClient<runtime.Types.Result.GetResult<Prisma.$init_tablePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Init_tables.
   * @param {init_tableCreateManyArgs} args - Arguments to create many Init_tables.
   * @example
   * // Create many Init_tables
   * const init_table = await prisma.init_table.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends init_tableCreateManyArgs>(args?: Prisma.SelectSubset<T, init_tableCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Init_table.
   * @param {init_tableDeleteArgs} args - Arguments to delete one Init_table.
   * @example
   * // Delete one Init_table
   * const Init_table = await prisma.init_table.delete({
   *   where: {
   *     // ... filter to delete one Init_table
   *   }
   * })
   * 
   */
  delete<T extends init_tableDeleteArgs>(args: Prisma.SelectSubset<T, init_tableDeleteArgs<ExtArgs>>): Prisma.Prisma__init_tableClient<runtime.Types.Result.GetResult<Prisma.$init_tablePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Init_table.
   * @param {init_tableUpdateArgs} args - Arguments to update one Init_table.
   * @example
   * // Update one Init_table
   * const init_table = await prisma.init_table.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends init_tableUpdateArgs>(args: Prisma.SelectSubset<T, init_tableUpdateArgs<ExtArgs>>): Prisma.Prisma__init_tableClient<runtime.Types.Result.GetResult<Prisma.$init_tablePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Init_tables.
   * @param {init_tableDeleteManyArgs} args - Arguments to filter Init_tables to delete.
   * @example
   * // Delete a few Init_tables
   * const { count } = await prisma.init_table.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends init_tableDeleteManyArgs>(args?: Prisma.SelectSubset<T, init_tableDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Init_tables.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {init_tableUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Init_tables
   * const init_table = await prisma.init_table.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends init_tableUpdateManyArgs>(args: Prisma.SelectSubset<T, init_tableUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Init_table.
   * @param {init_tableUpsertArgs} args - Arguments to update or create a Init_table.
   * @example
   * // Update or create a Init_table
   * const init_table = await prisma.init_table.upsert({
   *   create: {
   *     // ... data to create a Init_table
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Init_table we want to update
   *   }
   * })
   */
  upsert<T extends init_tableUpsertArgs>(args: Prisma.SelectSubset<T, init_tableUpsertArgs<ExtArgs>>): Prisma.Prisma__init_tableClient<runtime.Types.Result.GetResult<Prisma.$init_tablePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Init_tables.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {init_tableCountArgs} args - Arguments to filter Init_tables to count.
   * @example
   * // Count the number of Init_tables
   * const count = await prisma.init_table.count({
   *   where: {
   *     // ... the filter for the Init_tables we want to count
   *   }
   * })
  **/
  count<T extends init_tableCountArgs>(
    args?: Prisma.Subset<T, init_tableCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Init_tableCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Init_table.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Init_tableAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Init_tableAggregateArgs>(args: Prisma.Subset<T, Init_tableAggregateArgs>): Prisma.PrismaPromise<GetInit_tableAggregateType<T>>

  /**
   * Group by Init_table.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {init_tableGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends init_tableGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: init_tableGroupByArgs['orderBy'] }
      : { orderBy?: init_tableGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, init_tableGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetInit_tableGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the init_table model
 */
readonly fields: init_tableFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for init_table.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__init_tableClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the init_table model
 */
export interface init_tableFieldRefs {
  readonly id: Prisma.FieldRef<"init_table", 'Int'>
}
    

// Custom InputTypes
/**
 * init_table findUnique
 */
export type init_tableFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the init_table
   */
  select?: Prisma.init_tableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the init_table
   */
  omit?: Prisma.init_tableOmit<ExtArgs> | null
  /**
   * Filter, which init_table to fetch.
   */
  where: Prisma.init_tableWhereUniqueInput
}

/**
 * init_table findUniqueOrThrow
 */
export type init_tableFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the init_table
   */
  select?: Prisma.init_tableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the init_table
   */
  omit?: Prisma.init_tableOmit<ExtArgs> | null
  /**
   * Filter, which init_table to fetch.
   */
  where: Prisma.init_tableWhereUniqueInput
}

/**
 * init_table findFirst
 */
export type init_tableFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the init_table
   */
  select?: Prisma.init_tableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the init_table
   */
  omit?: Prisma.init_tableOmit<ExtArgs> | null
  /**
   * Filter, which init_table to fetch.
   */
  where?: Prisma.init_tableWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of init_tables to fetch.
   */
  orderBy?: Prisma.init_tableOrderByWithRelationInput | Prisma.init_tableOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for init_tables.
   */
  cursor?: Prisma.init_tableWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` init_tables from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` init_tables.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of init_tables.
   */
  distinct?: Prisma.Init_tableScalarFieldEnum | Prisma.Init_tableScalarFieldEnum[]
}

/**
 * init_table findFirstOrThrow
 */
export type init_tableFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the init_table
   */
  select?: Prisma.init_tableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the init_table
   */
  omit?: Prisma.init_tableOmit<ExtArgs> | null
  /**
   * Filter, which init_table to fetch.
   */
  where?: Prisma.init_tableWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of init_tables to fetch.
   */
  orderBy?: Prisma.init_tableOrderByWithRelationInput | Prisma.init_tableOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for init_tables.
   */
  cursor?: Prisma.init_tableWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` init_tables from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` init_tables.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of init_tables.
   */
  distinct?: Prisma.Init_tableScalarFieldEnum | Prisma.Init_tableScalarFieldEnum[]
}

/**
 * init_table findMany
 */
export type init_tableFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the init_table
   */
  select?: Prisma.init_tableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the init_table
   */
  omit?: Prisma.init_tableOmit<ExtArgs> | null
  /**
   * Filter, which init_tables to fetch.
   */
  where?: Prisma.init_tableWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of init_tables to fetch.
   */
  orderBy?: Prisma.init_tableOrderByWithRelationInput | Prisma.init_tableOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing init_tables.
   */
  cursor?: Prisma.init_tableWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` init_tables from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` init_tables.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of init_tables.
   */
  distinct?: Prisma.Init_tableScalarFieldEnum | Prisma.Init_tableScalarFieldEnum[]
}

/**
 * init_table create
 */
export type init_tableCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the init_table
   */
  select?: Prisma.init_tableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the init_table
   */
  omit?: Prisma.init_tableOmit<ExtArgs> | null
  /**
   * The data needed to create a init_table.
   */
  data?: Prisma.XOR<Prisma.init_tableCreateInput, Prisma.init_tableUncheckedCreateInput>
}

/**
 * init_table createMany
 */
export type init_tableCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many init_tables.
   */
  data: Prisma.init_tableCreateManyInput | Prisma.init_tableCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * init_table update
 */
export type init_tableUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the init_table
   */
  select?: Prisma.init_tableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the init_table
   */
  omit?: Prisma.init_tableOmit<ExtArgs> | null
  /**
   * The data needed to update a init_table.
   */
  data: Prisma.XOR<Prisma.init_tableUpdateInput, Prisma.init_tableUncheckedUpdateInput>
  /**
   * Choose, which init_table to update.
   */
  where: Prisma.init_tableWhereUniqueInput
}

/**
 * init_table updateMany
 */
export type init_tableUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update init_tables.
   */
  data: Prisma.XOR<Prisma.init_tableUpdateManyMutationInput, Prisma.init_tableUncheckedUpdateManyInput>
  /**
   * Filter which init_tables to update
   */
  where?: Prisma.init_tableWhereInput
  /**
   * Limit how many init_tables to update.
   */
  limit?: number
}

/**
 * init_table upsert
 */
export type init_tableUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the init_table
   */
  select?: Prisma.init_tableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the init_table
   */
  omit?: Prisma.init_tableOmit<ExtArgs> | null
  /**
   * The filter to search for the init_table to update in case it exists.
   */
  where: Prisma.init_tableWhereUniqueInput
  /**
   * In case the init_table found by the `where` argument doesn't exist, create a new init_table with this data.
   */
  create: Prisma.XOR<Prisma.init_tableCreateInput, Prisma.init_tableUncheckedCreateInput>
  /**
   * In case the init_table was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.init_tableUpdateInput, Prisma.init_tableUncheckedUpdateInput>
}

/**
 * init_table delete
 */
export type init_tableDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the init_table
   */
  select?: Prisma.init_tableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the init_table
   */
  omit?: Prisma.init_tableOmit<ExtArgs> | null
  /**
   * Filter which init_table to delete.
   */
  where: Prisma.init_tableWhereUniqueInput
}

/**
 * init_table deleteMany
 */
export type init_tableDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which init_tables to delete
   */
  where?: Prisma.init_tableWhereInput
  /**
   * Limit how many init_tables to delete.
   */
  limit?: number
}

/**
 * init_table without action
 */
export type init_tableDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the init_table
   */
  select?: Prisma.init_tableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the init_table
   */
  omit?: Prisma.init_tableOmit<ExtArgs> | null
}
