
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.7.0
 * Query Engine version: 75cbdc1eb7150937890ad5465d861175c6624711
 */
Prisma.prismaVersion = {
  client: "7.7.0",
  engine: "75cbdc1eb7150937890ad5465d861175c6624711"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.AdminUserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  password: 'password',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InvitationScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VenueLocationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  address: 'address',
  latitude: 'latitude',
  longitude: 'longitude',
  popupImageUrl: 'popupImageUrl',
  eventType: 'eventType',
  mapZoom: 'mapZoom',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  invitationId: 'invitationId'
};

exports.Prisma.EventScheduleScalarFieldEnum = {
  id: 'id',
  title: 'title',
  date: 'date',
  startTime: 'startTime',
  endTime: 'endTime',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  invitationId: 'invitationId'
};

exports.Prisma.RSVPSubmissionScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  attendanceStatus: 'attendanceStatus',
  paxCount: 'paxCount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  invitationId: 'invitationId',
  idempotencyKey: 'idempotencyKey'
};

exports.Prisma.GuestbookEntryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  message: 'message',
  isVisible: 'isVisible',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  invitationId: 'invitationId',
  idempotencyKey: 'idempotencyKey'
};

exports.Prisma.CashlessAccountScalarFieldEnum = {
  id: 'id',
  bankName: 'bankName',
  accountNumber: 'accountNumber',
  accountHolderName: 'accountHolderName',
  bankLogoUrl: 'bankLogoUrl',
  qrCodeUrl: 'qrCodeUrl',
  sortOrder: 'sortOrder',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  invitationId: 'invitationId'
};

exports.Prisma.GiftAddressScalarFieldEnum = {
  id: 'id',
  label: 'label',
  recipientName: 'recipientName',
  phone: 'phone',
  address: 'address',
  postalCode: 'postalCode',
  note: 'note',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  invitationId: 'invitationId'
};

exports.Prisma.StoryImageScalarFieldEnum = {
  id: 'id',
  imageUrl: 'imageUrl',
  caption: 'caption',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  storyItemId: 'storyItemId'
};

exports.Prisma.InvitationConfigScalarFieldEnum = {
  id: 'id',
  heroCoupleNames: 'heroCoupleNames',
  heroOpeningLine: 'heroOpeningLine',
  heroWeddingDateText: 'heroWeddingDateText',
  heroBackgroundImage: 'heroBackgroundImage',
  weddingDate: 'weddingDate',
  primaryColor: 'primaryColor',
  secondaryColor: 'secondaryColor',
  backgroundColor: 'backgroundColor',
  textColor: 'textColor',
  backgroundMusicUrl: 'backgroundMusicUrl',
  footerGreeting: 'footerGreeting',
  footerClosingText: 'footerClosingText',
  lockedLandingEnabled: 'lockedLandingEnabled',
  lockedLandingButtonText: 'lockedLandingButtonText',
  lockedLandingGreeting: 'lockedLandingGreeting',
  musicEnabled: 'musicEnabled',
  musicButtonPosition: 'musicButtonPosition',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  invitationId: 'invitationId'
};

exports.Prisma.CoupleInfoScalarFieldEnum = {
  id: 'id',
  groomName: 'groomName',
  brideName: 'brideName',
  groomParents: 'groomParents',
  brideParents: 'brideParents',
  greetingText: 'greetingText',
  couplePhotoUrl: 'couplePhotoUrl',
  groomPhotoUrl: 'groomPhotoUrl',
  bridePhotoUrl: 'bridePhotoUrl',
  groomSocialLink: 'groomSocialLink',
  brideSocialLink: 'brideSocialLink',
  bibleVerse: 'bibleVerse',
  bibleReference: 'bibleReference',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  invitationId: 'invitationId'
};

exports.Prisma.StoryItemScalarFieldEnum = {
  id: 'id',
  title: 'title',
  body: 'body',
  imageUrl: 'imageUrl',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  invitationId: 'invitationId'
};

exports.Prisma.GalleryImageScalarFieldEnum = {
  id: 'id',
  imageUrl: 'imageUrl',
  caption: 'caption',
  sortOrder: 'sortOrder',
  aspectRatio: 'aspectRatio',
  isFeatured: 'isFeatured',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  invitationId: 'invitationId'
};

exports.Prisma.PhilosophyConfigScalarFieldEnum = {
  id: 'id',
  quoteText: 'quoteText',
  quoteMeaning: 'quoteMeaning',
  prayerText: 'prayerText',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  invitationId: 'invitationId'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.AdminUserOrderByRelevanceFieldEnum = {
  username: 'username',
  password: 'password'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.VenueLocationOrderByRelevanceFieldEnum = {
  name: 'name',
  address: 'address',
  popupImageUrl: 'popupImageUrl',
  eventType: 'eventType'
};

exports.Prisma.EventScheduleOrderByRelevanceFieldEnum = {
  title: 'title'
};

exports.Prisma.RSVPSubmissionOrderByRelevanceFieldEnum = {
  name: 'name',
  email: 'email',
  idempotencyKey: 'idempotencyKey'
};

exports.Prisma.GuestbookEntryOrderByRelevanceFieldEnum = {
  name: 'name',
  message: 'message',
  idempotencyKey: 'idempotencyKey'
};

exports.Prisma.CashlessAccountOrderByRelevanceFieldEnum = {
  bankName: 'bankName',
  accountNumber: 'accountNumber',
  accountHolderName: 'accountHolderName',
  bankLogoUrl: 'bankLogoUrl',
  qrCodeUrl: 'qrCodeUrl'
};

exports.Prisma.GiftAddressOrderByRelevanceFieldEnum = {
  label: 'label',
  recipientName: 'recipientName',
  phone: 'phone',
  address: 'address',
  postalCode: 'postalCode',
  note: 'note'
};

exports.Prisma.StoryImageOrderByRelevanceFieldEnum = {
  imageUrl: 'imageUrl',
  caption: 'caption'
};

exports.Prisma.InvitationConfigOrderByRelevanceFieldEnum = {
  heroCoupleNames: 'heroCoupleNames',
  heroOpeningLine: 'heroOpeningLine',
  heroWeddingDateText: 'heroWeddingDateText',
  heroBackgroundImage: 'heroBackgroundImage',
  primaryColor: 'primaryColor',
  secondaryColor: 'secondaryColor',
  backgroundColor: 'backgroundColor',
  textColor: 'textColor',
  backgroundMusicUrl: 'backgroundMusicUrl',
  footerGreeting: 'footerGreeting',
  footerClosingText: 'footerClosingText',
  lockedLandingButtonText: 'lockedLandingButtonText',
  lockedLandingGreeting: 'lockedLandingGreeting',
  musicButtonPosition: 'musicButtonPosition'
};

exports.Prisma.CoupleInfoOrderByRelevanceFieldEnum = {
  groomName: 'groomName',
  brideName: 'brideName',
  groomParents: 'groomParents',
  brideParents: 'brideParents',
  greetingText: 'greetingText',
  couplePhotoUrl: 'couplePhotoUrl',
  groomPhotoUrl: 'groomPhotoUrl',
  bridePhotoUrl: 'bridePhotoUrl',
  groomSocialLink: 'groomSocialLink',
  brideSocialLink: 'brideSocialLink',
  bibleVerse: 'bibleVerse',
  bibleReference: 'bibleReference'
};

exports.Prisma.StoryItemOrderByRelevanceFieldEnum = {
  title: 'title',
  body: 'body',
  imageUrl: 'imageUrl'
};

exports.Prisma.GalleryImageOrderByRelevanceFieldEnum = {
  imageUrl: 'imageUrl',
  caption: 'caption',
  aspectRatio: 'aspectRatio'
};

exports.Prisma.PhilosophyConfigOrderByRelevanceFieldEnum = {
  quoteText: 'quoteText',
  quoteMeaning: 'quoteMeaning',
  prayerText: 'prayerText'
};
exports.AttendanceStatus = exports.$Enums.AttendanceStatus = {
  ATTENDING: 'ATTENDING',
  NOT_ATTENDING: 'NOT_ATTENDING'
};

exports.Prisma.ModelName = {
  AdminUser: 'AdminUser',
  Invitation: 'Invitation',
  VenueLocation: 'VenueLocation',
  EventSchedule: 'EventSchedule',
  RSVPSubmission: 'RSVPSubmission',
  GuestbookEntry: 'GuestbookEntry',
  CashlessAccount: 'CashlessAccount',
  GiftAddress: 'GiftAddress',
  StoryImage: 'StoryImage',
  InvitationConfig: 'InvitationConfig',
  CoupleInfo: 'CoupleInfo',
  StoryItem: 'StoryItem',
  GalleryImage: 'GalleryImage',
  PhilosophyConfig: 'PhilosophyConfig'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
